In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score
import pandas as pd 

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [5]:
data  ={
    "hours" : [1,2,3,4,5,6,7,8,9,10],
    "attendence": [40,45,50,55,60,65,70,75,80,85],
    "eligible" : [0,0,0,0,1,1,1,1,1,1]

}

df = pd.DataFrame(data)
df


hours  attendence  eligible
0      1          40         0
1      2          45         0
2      3          50         0
3      4          55         0
4      5          60         1
5      6          65         1
6      7          70         1
7      8          75         1
8      9          80         1
9     10          85         1

In [8]:
X = df[["hours", "attendence"]]
y= df["eligible"]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [10]:
model = LogisticRegression()

In [11]:
model.fit(X_train, y_train)

LogisticRegression()

In [12]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 1])

In [16]:
pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred,
    "Hours": X_test["hours"].values,
    "Attendence": X_test["attendence"].values


})


Actual  Predicted  Hours  Attendence
0       1          1      9          80
1       0          0      2          45
2       1          1      6          65

In [17]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm


array([[1, 0],
       [0, 2]])

In [18]:
y_probs= model.predict_proba(X_test)[:,1]
y_probs

array([9.99999939e-01, 9.55840550e-05, 9.96041120e-01])

In [19]:
y_pred_default= (y_probs >= 0.5).astype(int)
y_pred_default

array([1, 0, 1])

In [21]:
threshold = 0.3
y_pred_low = (y_probs >= threshold).astype(int)
y_pred_low

array([1, 0, 1])

In [27]:
pd.DataFrame({
    "Hours": X_test["hours"].values,
    "Attendence": X_test["attendence"].values,
    "Actual": y_test.values,
    "Predicted_0.5": y_pred_default,
    "Predicted_0.3": y_pred_low,
    "Prob_Eligible": y_probs

})


Hours  Attendence  Actual  Predicted_0.5  Predicted_0.3  Prob_Eligible
0      9          80       1              1              1       1.000000
1      2          45       0              0              0       0.000096
2      6          65       1              1              1       0.996041

In [28]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score

print("Default threshold (0.5)")
print(confusion_matrix(y_test, y_pred_default))
print("Precision:", precision_score(y_test, y_pred_default))
print("Recall:", recall_score(y_test, y_pred_default))

print("\nLower threshold (0.3)")
print(confusion_matrix(y_test, y_pred_low))
print("Precision:", precision_score(y_test, y_pred_low))
print("Recall:", recall_score(y_test, y_pred_low))


Default threshold (0.5)
[[1 0]
 [0 2]]
Precision: 1.0
Recall: 1.0

Lower threshold (0.3)
[[1 0]
 [0 2]]
Precision: 1.0
Recall: 1.0
